### PR TITLE
Add dark/light theme option

### PR DESCRIPTION
**Pull request by krt16s**
Add preference screen with option to toggle between dark and light theme. Preference screen is disabled on API < 14 due to crashing.

### CODE REVIEW

**Comment by dschuermann** [comment]
I tested the pull request, it works okay:
* can you add white icons, at least for the close button when editing a calendar

**Comment by krt16s** [comment]
Done in 70ba955b5d804788ace9886b4d808a4045147c38, but there is more likely a easier and better way. I clutter the source with ifs.. anyway, works for me. This PR should auto-update once github finishes its hickup..

**Comment by dschuermann** [comment]
accidental close?

**Comment by krt16s** [comment]
Yeah.. github had yesterday an outtake and didn't update the PR. Should be fine now.

**Comment by krt16s** [comment]
Ping?

**Comment by dschuermann** [comment]
Sry, I have now merged it!

**Pull request merged**
